"""create tenants table

Revision ID: 460885cc8401
Revises: 
Create Date: 2025-04-20 23:37:45.471711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '460885cc8401'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('schema_name', sa.String(length=63), nullable=False),
        sa.Column('subdomain', sa.String(length=100), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_tenants')),
        sa.UniqueConstraint('name', name=op.f('uq_tenants_name')),
        schema='public'
    )
    op.create_index(op.f('ix_public_tenants_id'), 'tenants', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_tenants_schema_name'), 'tenants', ['schema_name'], unique=True, schema='public')
    op.create_index(op.f('ix_public_tenants_subdomain'), 'tenants', ['subdomain'], unique=True, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_tenants_subdomain'), table_name='tenants', schema='public')
    op.drop_index(op.f('ix_public_tenants_schema_name'), table_name='tenants', schema='public')
    op.drop_index(op.f('ix_public_tenants_id'), table_name='tenants', schema='public')
    op.drop_table('tenants', schema='public')
    # ### end Alembic commands ###
